name: Test CI
on: [ push, fork ]

jobs:
  TEST_ALL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 🪜 Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: 🦞 chmod /gradlew
        run:  chmod +x ./gradlew

      - name: 🔦 Tes 🎚
        run: ./gradlew test --info
